name: Vale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@v2
        with:
          config: .vale.ini
          styles-path: ..vale/google
